### ISSUE TITLE
How to run a class that extends SfCommand ?

### ISSUE THREAD

**Issue by RemyVULTAGGIO** [salesforcecli/sf-plugins-core#200]
Hi,

This is not an issue but I can't find anywhere else to post this question.
I spent many time browsing forums and sources from salesforcecli projects but can't find anything to help me.

I would like to make a direct call (not a child_process exec or so) in my SFDX plugin to a class that extends SfCommand but I struggle with constructor args.

When I try to directly call a class that extends SfdxCommand, it works perfectly :
import { OrgListCommand } from '@salesforce/plugin-org/lib/commands/force/org/list';
[...]
const orgListCommand = new OrgListCommand(['--all', '--json'], {});
const rawResponse = await orgListCommand._run();

Right now, I am trying to make the following lines work :
import { PackageInstalledListCommand } from '@salesforce/plugin-packaging/lib/commands/package/installed/list';
[...]
const packageInstalledListCommand = new PackageInstalledListCommand([`--targetusername ${orgAliasTmp}`, '--json'], {});
const installedPackagesRawResponse = await packageInstalledListCommand._run();

(By the way, I can't find where the 'legacy' commands are... If you know, please tell me)

I made several tries :
First, it crashed on a 'config.plugins' error. So I tried to set the command config arg with '{ plugins: [] }'.
Then, it crashed on a 'config.scopedEnvVarKey' error. So I tried to set the command config arg with '{ plugins: [], scopedEnvVarKey: (k: string): string => { return k.replace(/-/g, '_').toUpperCase(); } }'. (From a piece of code I found in a salesforcecli project. It already seems pretty obvious that I was not on the right track)
Nevermind, it crashed on 'Unexpected argument: --targetusername' error.
So I tried to name the argument 'target-org'. Etc.
...

At the end of the day, I don't know if the problem comes from the way I call the class that extends SfCommand or if it is the called class itself. (I'm pretty sure, it is the first one as test on other classes went wrong too)

Thanks in advance for your help.

Rémy

**Comment by shetzel** [comment]
This test in plugin-packaging shows an example: https://github.com/salesforcecli/plugin-packaging/blob/main/test/commands/package/install.test.ts#L137

Since this is essentially a cli question I would ask on https://github.com/forcedotcom/cli/issues but I think the link above should unblock you.

**Comment by RemyVULTAGGIO** [comment]
Thanks @shetzel, the test class helped me !    :)
