### ISSUE TITLE
TypeError: this.config.getPluginsList is not a function

### ISSUE THREAD

**Issue by mbergal** [salesforcecli/sf-plugins-core#379]
```
> sf package version list
TypeError: this.config.getPluginsList is not a function
```
Since `@salesforce/plugin-packaging` does not pin the `@sakesforce/sf-plugins-core`, our build infra is currently broken.

**Comment by avesolovksyy** [comment]
Same story here - all our CI/CD pipelines which make calls to 'sf package version create/install/list' are failing with
` TypeError: this.config.getPluginsList is not a function`

No stack trace, just single error message ant that is it.
There were no changes from our side: neither in code base, neither in pipeline configs.
Even when we've tried to re-run yesterday's successful pipelines, we are getting back same error now.

Seems like a global issue.

**Comment by mbergal** [comment]
Hacked it like this on our CI:

```
- name: Install packaging plugin (temp super hack)
              run: |
                  npm i @salesforce/plugin-packaging --global && sf plugins link $(npm list -g -p | grep plugin-packaging)
                  npm i @salesforce/sf-plugins-core@3.1.17
                  cp -r $(npm list -p | grep sf-plugins-core) $(npm list -p -g | grep plugin-packaging)/node_modules/@salesforce
```

**Comment by cristiand391** [comment]
Hey all, we released a patch in the CLI that should fix this, see: https://github.com/forcedotcom/cli/issues/2426#issuecomment-1692011450
